-- =============================================================================
-- Caja y ventas
-- =============================================================================

-- Turno de caja: se abre con un fondo inicial y se cierra contando el efectivo.
create table public.cash_session (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id),
  opened_at timestamptz not null default now(),
  opening_amount numeric(10, 2) not null default 0,
  closed_at timestamptz,
  expected_cash numeric(10, 2),        -- fondo + ventas en efectivo (al cerrar)
  counted_cash numeric(10, 2),         -- lo que contó el cajero
  note text
);
-- Un solo turno abierto por usuario.
create unique index cash_session_open_idx on public.cash_session (user_id) where closed_at is null;

create type public.payment_method as enum ('efectivo', 'yape', 'plin', 'tarjeta', 'transferencia');
create type public.sale_status as enum ('completada', 'anulada');

create table public.sale (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity (start with 1) unique,
  status public.sale_status not null default 'completada',
  cash_session_id uuid references public.cash_session (id) on delete set null,
  user_id uuid references auth.users (id) on delete set null,
  customer_id uuid references public.customer (id) on delete set null,
  customer_name text,
  customer_doc text,
  payment_method public.payment_method not null default 'efectivo',
  amount_received numeric(10, 2),      -- solo efectivo
  change_given numeric(10, 2),
  discount_total numeric(10, 2) not null default 0,
  subtotal numeric(10, 2) not null default 0,   -- base imponible (sin IGV)
  igv numeric(10, 2) not null default 0,
  total numeric(10, 2) not null default 0,       -- lo que paga el cliente (IGV incluido)
  cost_total numeric(10, 2) not null default 0,
  item_count int not null default 0,
  note text,
  created_at timestamptz not null default now(),
  voided_at timestamptz,
  voided_by uuid references auth.users (id) on delete set null,
  void_reason text
);
create index sale_created_idx on public.sale (created_at desc);
create index sale_session_idx on public.sale (cash_session_id);

create type public.sale_unit as enum ('unidad', 'caja');

create table public.sale_item (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sale (id) on delete cascade,
  product_id uuid references public.product (id) on delete set null,
  product_name text not null,
  description text,                    -- concentración / presentación en el ticket
  unit public.sale_unit not null default 'unidad',
  quantity int not null check (quantity > 0),   -- en la unidad elegida
  units int not null check (units > 0),         -- en unidades de stock
  unit_price numeric(10, 2) not null,
  discount numeric(10, 2) not null default 0,
  total numeric(10, 2) not null,
  cost_total numeric(10, 2) not null default 0,
  igv_exempt boolean not null default false
);
create index sale_item_sale_idx on public.sale_item (sale_id);
create index sale_item_product_idx on public.sale_item (product_id);

-- De qué lotes salió cada línea (FEFO: primero el que vence antes). Permite anular.
create table public.sale_item_lot (
  sale_item_id uuid not null references public.sale_item (id) on delete cascade,
  lot_id uuid not null references public.lot (id) on delete cascade,
  units int not null check (units > 0),
  primary key (sale_item_id, lot_id)
);
