-- =============================================================================
-- Catálogo e inventario por lotes (con fecha de vencimiento)
-- Todo el stock se cuenta en UNIDADES (tableta, frasco, sobre…). Una "caja" son
-- units_per_pack unidades.
-- =============================================================================

create table public.category (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  color text not null default '#5c6ac4',
  rank int not null default 0,
  created_at timestamptz not null default now()
);

create table public.supplier (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  ruc text,
  phone text,
  contact text,
  created_at timestamptz not null default now()
);

create type public.dosage_form as enum ('tableta', 'capsula', 'jarabe', 'suspension', 'gotas', 'crema', 'gel', 'unguento', 'inyectable', 'sobre', 'inhalador', 'ovulo', 'solucion', 'spray', 'otro');

create table public.product (
  id uuid primary key default gen_random_uuid(),
  name text not null,                           -- nombre comercial: "Panadol Antigripal"
  generic_name text,                            -- principio activo / DCI: "Paracetamol + Fenilefrina"
  concentration text,                           -- "500 mg", "120 mg/5 mL"
  form public.dosage_form not null default 'tableta',
  presentation text,                            -- "Caja x 100 tabletas"
  laboratory text,
  category_id uuid references public.category (id) on delete set null,
  barcode text unique,
  code text unique,                             -- código interno
  units_per_pack int not null default 1 check (units_per_pack >= 1),
  sell_by_unit boolean not null default true,   -- ¿se vende fraccionado (por unidad)?
  price_unit numeric(10, 2) not null default 0 check (price_unit >= 0),
  price_pack numeric(10, 2) check (price_pack >= 0),   -- precio por caja (si es distinto a unidad × N)
  cost_unit numeric(10, 4) not null default 0,          -- costo promedio por unidad
  min_stock int not null default 0,             -- en unidades; por debajo = "stock bajo"
  requires_prescription boolean not null default false,
  is_controlled boolean not null default false,
  igv_exempt boolean not null default false,
  location text,                                -- estante / vitrina
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index product_category_idx on public.product (category_id);
create index product_search_idx on public.product using gin ((internal.norm(name || ' ' || coalesce(generic_name, '') || ' ' || coalesce(laboratory, ''))) extensions.gin_trgm_ops);
create trigger product_updated_at before update on public.product for each row execute function internal.set_updated_at();

create table public.customer (
  id uuid primary key default gen_random_uuid(),
  doc_type text not null default 'DNI' check (doc_type in ('DNI', 'RUC', 'CE', 'PAS')),
  doc_number text not null unique,
  name text not null,
  phone text,
  created_at timestamptz not null default now()
);

-- Lotes: cada ingreso de mercadería crea (o suma a) un lote con su vencimiento.
create table public.lot (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.product (id) on delete cascade,
  lot_number text not null,
  expiry_date date,
  quantity int not null default 0 check (quantity >= 0),
  cost_unit numeric(10, 4) not null default 0,
  received_at timestamptz not null default now(),
  unique (product_id, lot_number, expiry_date)
);
create index lot_product_idx on public.lot (product_id, expiry_date);

-- Ingreso de mercadería (compra a proveedor)
create table public.purchase (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity (start with 1) unique,
  supplier_id uuid references public.supplier (id) on delete set null,
  invoice_number text,
  total numeric(12, 2) not null default 0,
  note text,
  user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.purchase_item (
  id uuid primary key default gen_random_uuid(),
  purchase_id uuid not null references public.purchase (id) on delete cascade,
  product_id uuid not null references public.product (id),
  lot_id uuid references public.lot (id) on delete set null,
  lot_number text not null,
  expiry_date date,
  units int not null check (units > 0),
  cost_unit numeric(10, 4) not null default 0,
  total numeric(12, 2) generated always as (round(units * cost_unit, 2)) stored
);

-- Kardex: todo movimiento de stock queda registrado.
create type public.movement_type as enum ('compra', 'venta', 'anulacion', 'ajuste', 'vencido', 'merma');

create table public.stock_movement (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.product (id) on delete cascade,
  lot_id uuid references public.lot (id) on delete set null,
  type public.movement_type not null,
  units int not null,                  -- + entra, − sale
  balance int not null,                -- stock total del producto después del movimiento
  reference_id uuid,                   -- venta o compra
  note text,
  user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);
create index stock_movement_product_idx on public.stock_movement (product_id, created_at desc);

-- Stock vendible = lotes no vencidos.
create or replace function internal.sellable_units(p_product uuid) returns int
language sql stable as $$
  select coalesce(sum(quantity), 0)::int from public.lot
  where product_id = p_product and quantity > 0 and (expiry_date is null or expiry_date >= internal.today())
$$;

create or replace function internal.total_units(p_product uuid) returns int
language sql stable as $$
  select coalesce(sum(quantity), 0)::int from public.lot where product_id = p_product
$$;

-- Vista de productos con su stock (la usan inventario, POS y panel).
create view public.product_stock with (security_invoker = true) as
select p.*,
       c.name as category_name,
       c.color as category_color,
       coalesce(s.sellable, 0)::int as stock,
       coalesce(s.expired, 0)::int as expired_units,
       s.next_expiry,
       coalesce(s.lots, 0)::int as lot_count,
       round(coalesce(s.sellable, 0) * p.cost_unit, 2) as stock_value,
       (coalesce(s.sellable, 0) <= p.min_stock) as is_low_stock
from public.product p
left join public.category c on c.id = p.category_id
left join lateral (
  select sum(l.quantity) filter (where l.expiry_date is null or l.expiry_date >= internal.today()) as sellable,
         sum(l.quantity) filter (where l.expiry_date < internal.today()) as expired,
         min(l.expiry_date) filter (where l.quantity > 0 and l.expiry_date >= internal.today()) as next_expiry,
         count(*) filter (where l.quantity > 0) as lots
  from public.lot l where l.product_id = p.id
) s on true;

-- Lotes con stock y días para vencer.
create view public.lot_status with (security_invoker = true) as
select l.*, p.name as product_name, p.generic_name, p.concentration, p.presentation, p.laboratory, p.units_per_pack,
       (l.expiry_date - internal.today()) as days_to_expiry,
       round(l.quantity * l.cost_unit, 2) as value
from public.lot l join public.product p on p.id = l.product_id
where l.quantity > 0;
